### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by ghost** [expressvpn/expressvpn_leak_testing#1]
Hi,
Thanks for making this available for starters! looks like a great addition to the toolkit.

I cant get the tests to run under Linux, all of the example configs i have tried in  in configs/case_studies just fail on my Linux box with an error as follows.

Traceback (most recent call last):
  File "/home/heyal/github/expressvpn_leak_testing/tools/../xv_leak_tools/test_execution/test_runner.py", line 314, in run_one
    step.up(test_run)
   File "/home/heyal/github/expressvpn_leak_testing/tools/../xv_leak_tools/test_execution/test_runner.py", line 269, in _execute_test
    test_run.test_class_instance().test()
   File "/home/heyal/github/expressvpn_leak_testing/tools/../desktop_local_tests/local_packet_capture_test_case.py", line 56, in test
    self.localhost['vpn_application'].open_and_connect()
   File "/home/heyal/github/expressvpn_leak_testing/tools/../xv_leak_tools/test_components/vpn_application/vpn_application.py", line 118, in open_and_connect
    self.connect()
   File "/home/heyal/github/expressvpn_leak_testing/tools/../xv_leak_tools/test_components/vpn_application/desktop_vpn_application.py", line 385, in connect
    self._routes_before_connect = self._device['route'].get_v4_routes()
   File "/home/heyal/github/expressvpn_leak_testing/tools/../xv_leak_tools/test_components/route/linux/linux_route.py", line 17, in get_v4_routes
    raise XVEx("TODO: get_v4_routes not implemented on linux")

Exception: XVEx: TODO: get_v4_routes not implemented on linux

Am I to assume that Linux support is still to come?

Thanks

**Comment by expressvpn** [comment]
Linux support is indeed a work in progress, but full support shouldn't be too far away. We've just pushed a commit which fixes the above issue and adds a few more tweaks for linux. The above issue was simply that a component for parsing the routing table on linux hadn't been implemented.

Please let us know if this fixes your issue and if you have any others.

Thanks for taking an interest in the tools btw!

**Comment by ghost** [comment]
Thats fixed that particular issue, thanks.
