### ISSUE TITLE
run test error code

### ISSUE THREAD

**Issue by WhiteFangWBC** [expressvpn/expressvpn_leak_testing#9]
$ ./run_tests.sh -c configs/case_studies/vanilla_leaks.py

errors code below:

`Unrecoverable error: Traceback (most recent call last):
  File "./tools/run_tests.py", line 177, in <module>
    sys.exit(main())
   File "./tools/run_tests.py", line 104, in main
    TestRunner.configure_logger(level=inital_log_level)
   File "/expressvpn_leak_testing-master/tools/../xv_leak_tools/test_execution/test_runner.py", line 131, in configure_logger
    'logfile': report_logfile,
   File "/expressvpn_leak_testing-master/tools/../xv_leak_tools/log.py", line 95, in configure
    LeakTestLogger._configure_logger('trace', **trace_settings)
   File "/expressvpn_leak_testing-master/tools/../xv_leak_tools/log.py", line 79, in _configure_logger
    formatter = colorlog.TTYColoredFormatter(fmt=stream_format, log_colors=log_colors)
   File "/home/BotNet/xv_leak_testing_python/lib/python3.6/site-packages/colorlog/colorlog.py", line 200, in __init__
    self.stream = kwargs.pop('stream')

Exception: 'stream'`

**Comment by 2bitsin** [comment]
Runing into the same issue 😢

**Comment by abielrodriguez** [comment]
Same error
